version: "3.9"

services:
  kalender:
    image: kalender-app
    container_name: kalender
    restart: "no"

    env_file:
      - .env.dev
    user: "1000:1000"


    volumes:
      - ./config:/app/config
      - ./Input_data:/app/Input_data
      - ./output:/app/output

